### ISSUE TITLE
Dry Run ranking

### ISSUE THREAD

**Issue by AyeshaNirma** [Ir1d/DARKFACE_eval_tools#11]
Hi Guys,

When will you guys upload the rankings for dryrun of track 2.2 ? I mean its already late ?

Thanks

**Comment by Ir1d** [comment]
Hi, the results of dryrun were sent via email some time ago, plz check your inbox and send email directly to the UG2+ track 2 organisers if you have any questions.
Best

**Comment by AyeshaNirma** [comment]
We did get our individual performances, but it was mentioned that we will also receive a dryrun leaderboard.
