### ISSUE TITLE
docker start failed

### ISSUE THREAD

**Issue by zhenxing9968** [Ir1d/DARKFACE_eval_tools#14]
Hi,
When I use the recommended command 'docker run --rm -it ....', I had some questions.

docker run failed,:

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
error: textscan: invalid stream number = -1
error: called from
    df_eval at line 15 column 11

**Comment by zhangboshen** [comment]
> Hi,
> When I use the recommended command 'docker run --rm -it ....', I had some questions.
> 
> docker run failed,:
> 
> octave: X11 DISPLAY environment variable not set
> octave: disabling GUI features
> error: textscan: invalid stream number = -1
> error: called from
> df_eval at line 15 column 11

@zhenxing9968  Hi, did you solve the problem? same thing here...
