### ISSUE TITLE
The mAP is 0.479 for DSFD using DSFD.mat

### ISSUE THREAD

**Issue by JaywongWang** [Ir1d/DARKFACE_eval_tools#3]
Hi,
I calculated mAP (area under the PR-curve) using mAP = np.trapz(DSFD[:,  0], DSFD[:, 1]), but got 0.479 instead of the reported 0.516 from the paper.  
I am not sure why.

**Comment by Ir1d** [comment]
Thank you for informing, the difference is caused by a bug in the code, we will update the arxiv version soon.
