### ISSUE TITLE
Could you please provide a more detailed input/output file format instruction?

### ISSUE THREAD

**Issue by desti-nation** [Ir1d/DARKFACE_eval_tools#5]
When I try the code:
`octave df_eval.m YOUR_ALGORITHM_NAME ./data/gt/ /root/UG2/Sub_challenge2_1/output/userid/output/submission_#/,`
the code need to create ./output file before. 
And could you provide the gt and submit txt data format like:
x1 y1 x2 y2 conf 
x1 y1 x2 y2 conf 
(x and y are int, conf is float)
or a more detailed instruction on how to run the code using octave?

**Comment by Ir1d** [comment]
example submit data file can be found at https://github.com/Ir1d/docker_sample/blob/master/submission/DSFD/predictions-ref/
please note that first line of gt file is the number of bounding boxes.

```bash
octave df_eval.m algorithm_name /path/to/ground/truth/ /path/to/predictions/
```

(these two paths are paths inside the docker image)

> the code need to create ./output file before.

If you mean `./data/file_list.txt` is missing, it can be generated easily. Each line contains a `./data/gt/xxx.txt` (like https://github.com/Ir1d/DARKFACE_eval_tools/blob/master/file_list.txt)
