### ISSUE TITLE
Why the predicted confidence will be normalized? 

### ISSUE THREAD

**Issue by desti-nation** [Ir1d/DARKFACE_eval_tools#6]
As seen in function `norm_score`. Why not use the original confidence score to calculate the AP?

**Comment by Ir1d** [comment]
Hi, thanks for pointing it out, the code was written a while ago and I didn't remember it clearly.
It norms the confidence score into [0,1], then we enumerate the threshold from 0 to 1 by 1/1000, to plot the precision-recall curve, so I think it's acceptable?

**Comment by desti-nation** [comment]
So will the result be the same with norm_score and w/o norm ? Is the normalization a usual method in the AP calculating process ?

**Comment by Ir1d** [comment]
I believe this is also used in WIDER FACE.
