### ISSUE TITLE
AP = 0 for perfect submission (i.e. predict=ground truth)

### ISSUE THREAD

**Issue by hengck23** [Ir1d/DARKFACE_eval_tools#9]
I try to put predict = ground truth box + score=1.
This gives a ap=0.

The YOUR_ALGORITHM_NAME.mat gives

.. Created by Octave 6.0.0, Thu May 09 10:21:16 2019 UTC <root@ff58cad34ac8>
.. name: pr_curve
.. type: matrix
.. rows: 1000
.. columns: 2
 NAN  0
 NAN  0
 NAN  0
...

I also note that if i try predict = ground truth box + score=random_number_between_0.9_to_1.0.
This gives a ap=0.84.

i would expect ap=1.00 for these two cases

**Comment by Ir1d** [comment]
@hengck23 can you elaborate on how you got ap=0.84? I can't reproduce this
